In [56]:
from mongoengine import *
import numpy as np
import datetime 
import pandas
from sklearn import *

In [57]:
connect("GDP-test", host = "localhost", port = 27017)
class Detection(Document):
    id_webcam = IntField(required=True)
    city = StringField(required=True)
    location = StringField(required=True)
    latitude = FloatField(required=True)
    longitude = FloatField(required=True)
    numPeople = IntField(required=True)
    date = DateTimeField(required=True)
    time = DateTimeField(required=True)
    type = IntField(required=True)
    weather_description = StringField()
    temperature = FloatField()
    day_of_week = IntField()

In [68]:
table = pandas.DataFrame(Detection.objects(city='Roma').as_pymongo())
print(table)
time, temperature, weather, numP = table['time'].dt.strftime('%H').astype(int),table['temperature'],table['weather_description'],table['numPeople']
time = np.asarray(time)
temperature = np.asarray(temperature)
weather = np.asarray(weather)
numP = np.asarray(numP)

                        _id  id_webcam  city      location   latitude  \
0  605b12ea43c9b1e63f53120d          1  Roma  PiazzaNavona  41.899139   
1  605b17151da44b11e152da66          1  Roma  PiazzaNavona  41.899139   
2  605b17511da44b11e152da67          1  Roma  PiazzaNavona  41.899139   
3  605b178d1da44b11e152da68          1  Roma  PiazzaNavona  41.899139   
4  605b17ca1da44b11e152da69          1  Roma  PiazzaNavona  41.899139   
5  605b18061da44b11e152da6a          1  Roma  PiazzaNavona  41.899139   
6  605b18421da44b11e152da6b          1  Roma  PiazzaNavona  41.899139   
7  605b187f1da44b11e152da6c          1  Roma  PiazzaNavona  41.899139   

   longitude  numPeople                    date                    time  type  \
0  12.473311          0 2021-03-24 11:22:29.231 2021-03-24 11:22:29.231     0   
1  12.473311          7 2021-03-24 11:40:09.800 2021-03-24 11:40:09.800     0   
2  12.473311         11 2021-03-24 11:41:09.889 2021-03-24 11:41:09.889     0   
3  12.473311      

In [59]:
weatherDict = {'clear sky':0}

In [60]:
for i in range(weather.size):
    weather[i] = weatherDict[weather[i]]

In [61]:
temperature = temperature.reshape(-1,1)
time = time.reshape(-1,1)
weather = weather.reshape(-1,1)
timeTemp = np.concatenate((time,temperature,weather),axis = 1)
print(timeTemp)
model = sklearn.linear_model.LinearRegression()
model.fit(timeTemp,numP) 

[[11 13.48 0]
 [11 13.47 0]
 [11 13.47 0]
 [11 13.47 0]
 [11 13.47 0]
 [11 13.47 0]
 [11 13.47 0]
 [11 13.47 0]]


LinearRegression()

Coefficients: 
 [    0.         -1057.14285714     0.        ]
