In [69]:
from mongoengine import *
import numpy as np
import datetime 
import pandas
from sklearn import *

In [70]:
connect("GDP-test", host = "localhost", port = 27017)
class Detection(Document):
    id_webcam = IntField(required=True)
    city = StringField(required=True)
    location = StringField(required=True)
    latitude = FloatField(required=True)
    longitude = FloatField(required=True)
    numPeople = IntField(required=True)
    date = DateTimeField(required=True)
    time = DateTimeField(required=True)
    type = IntField(required=True)
    weather_description = StringField()
    temperature = FloatField()
    day_of_week = IntField()

In [73]:
print(Detection.objects.distinct('city'))
table = pandas.DataFrame(Detection.objects(city='Roma').as_pymongo())
print(table)
time, temperature, weather, numP = table['time'].dt.strftime('%H').astype(int),table['temperature'],table['weather_description'],table['numPeople']
time = np.asarray(time)
temperature = np.asarray(temperature)
weather = np.asarray(weather)
numP = np.asarray(numP)

['Roma', 'Novska', 'Djakovo', 'Krk']
                           _id  id_webcam  city      location   latitude  \
0     605af2081444b4c212abb284          1  Roma  PiazzaNavona  41.899139   
1     605af3351444b4c212abb285          1  Roma  PiazzaNavona  41.899139   
2     605af4601444b4c212abb286          1  Roma  PiazzaNavona  41.899139   
3     605af58c1444b4c212abb287          1  Roma  PiazzaNavona  41.899139   
4     605af6b81444b4c212abb288          1  Roma  PiazzaNavona  41.899139   
...                        ...        ...   ...           ...        ...   
1411  606175af9d07e17d925a90d7          1  Roma  PiazzaNavona  41.899139   
1412  606176dc9d07e17d925a90db          1  Roma  PiazzaNavona  41.899139   
1413  606178079d07e17d925a90df          1  Roma  PiazzaNavona  41.899139   
1414  606179339d07e17d925a90e3          1  Roma  PiazzaNavona  41.899139   
1415  60617a5f9d07e17d925a90e7          1  Roma  PiazzaNavona  41.899139   

      longitude  numPeople                    date

In [59]:
weatherDict = {'clear sky':0}

In [60]:
for i in range(weather.size):
    weather[i] = weatherDict[weather[i]]

In [61]:
temperature = temperature.reshape(-1,1)
time = time.reshape(-1,1)
weather = weather.reshape(-1,1)
timeTemp = np.concatenate((time,temperature,weather),axis = 1)
print(timeTemp)
model = sklearn.linear_model.LinearRegression()
model.fit(timeTemp,numP) 

[[11 13.48 0]
 [11 13.47 0]
 [11 13.47 0]
 [11 13.47 0]
 [11 13.47 0]
 [11 13.47 0]
 [11 13.47 0]
 [11 13.47 0]]


LinearRegression()

Coefficients: 
 [    0.         -1057.14285714     0.        ]
